
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tect-test-back-end-jm
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=data_kepegawaian
    restart: unless-stopped
    volumes:
      - ./views:/app/views
      - ./public:/app/public
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: tect-test-db-jm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_kepegawaian
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
